export interface QuizQuestion {
  q: string;
  options: string[];
  answer: number;
}

export const quizByCourse: Record<string, QuizQuestion[]> = {
  lkg: [
    { q: "Which letter comes after 'A'?", options: ["C", "B", "D", "E"], answer: 1 },
    { q: "How many eyes do you have?", options: ["1", "3", "2", "4"], answer: 2 },
    { q: "What color is the sky?", options: ["Red", "Green", "Blue", "Yellow"], answer: 2 },
    { q: "Which shape has 3 sides?", options: ["Circle", "Square", "Triangle", "Rectangle"], answer: 2 },
    { q: "What sound does a cat make?", options: ["Woof", "Meow", "Moo", "Baa"], answer: 1 },
  ],
  ukg: [
    { q: "What is the Tamil word for 'Water'?", options: ["நீர்", "தீ", "காற்று", "மண்"], answer: 0 },
    { q: "What comes after 10?", options: ["9", "11", "12", "8"], answer: 1 },
    { q: "Which is a fruit?", options: ["Carrot", "Potato", "Apple", "Onion"], answer: 2 },
    { q: "How many days in a week?", options: ["5", "6", "7", "8"], answer: 2 },
    { q: "Which animal gives us milk?", options: ["Dog", "Cat", "Cow", "Hen"], answer: 2 },
  ],
  primary: [
    { q: "What is 15 + 27?", options: ["41", "42", "43", "44"], answer: 1 },
    { q: "Which planet is closest to the Sun?", options: ["Venus", "Mercury", "Earth", "Mars"], answer: 1 },
    { q: "What is H₂O?", options: ["Hydrogen", "Oxygen", "Water", "Carbon"], answer: 2 },
    { q: "Who is the father of our nation?", options: ["Nehru", "Gandhi", "Bose", "Patel"], answer: 1 },
    { q: "How many states in India?", options: ["28", "29", "30", "27"], answer: 0 },
  ],
  middle: [
    { q: "Square root of 144?", options: ["11", "12", "13", "14"], answer: 1 },
    { q: "Which gas do plants absorb?", options: ["O₂", "N₂", "CO₂", "H₂"], answer: 2 },
    { q: "Who wrote Thirukkural?", options: ["Kambar", "Thiruvalluvar", "Bharathi", "Ilango"], answer: 1 },
    { q: "What is the SI unit of force?", options: ["Joule", "Newton", "Watt", "Pascal"], answer: 1 },
    { q: "Which river is the longest in India?", options: ["Yamuna", "Godavari", "Ganga", "Krishna"], answer: 2 },
  ],
  high: [
    { q: "What is the chemical formula of glucose?", options: ["C₆H₁₂O₆", "C₂H₅OH", "CH₄", "NaCl"], answer: 0 },
    { q: "Ohm's law relates V, I and?", options: ["P", "R", "C", "L"], answer: 1 },
    { q: "Who discovered gravity?", options: ["Einstein", "Newton", "Galileo", "Kepler"], answer: 1 },
    { q: "What is the LCM of 12 and 18?", options: ["24", "36", "48", "72"], answer: 1 },
    { q: "Photosynthesis occurs in?", options: ["Mitochondria", "Nucleus", "Chloroplast", "Ribosome"], answer: 2 },
  ],
  hsc: [
    { q: "Derivative of sin(x) is?", options: ["cos(x)", "-cos(x)", "tan(x)", "-sin(x)"], answer: 0 },
    { q: "Which element has atomic number 79?", options: ["Silver", "Gold", "Platinum", "Copper"], answer: 1 },
    { q: "Speed of light is approximately?", options: ["3×10⁶ m/s", "3×10⁸ m/s", "3×10¹⁰ m/s", "3×10⁴ m/s"], answer: 1 },
    { q: "Binary of 10 (decimal)?", options: ["1010", "1100", "1001", "1000"], answer: 0 },
    { q: "pH of pure water at 25°C?", options: ["6", "7", "8", "5"], answer: 1 },
  ],
  engineering: [
    { q: "Big-O of binary search?", options: ["O(n)", "O(log n)", "O(n²)", "O(1)"], answer: 1 },
    { q: "Kirchhoff's Current Law states sum of currents at a node is?", options: ["Maximum", "Zero", "One", "Infinity"], answer: 1 },
    { q: "Laplace transform of 1 is?", options: ["1/s", "s", "1/s²", "1"], answer: 0 },
    { q: "Which data structure uses LIFO?", options: ["Queue", "Stack", "Array", "Tree"], answer: 1 },
    { q: "Carnot efficiency depends on?", options: ["Pressure", "Volume", "Temperature", "Mass"], answer: 2 },
  ],
  mbbs: [
    { q: "Largest organ in the human body?", options: ["Liver", "Skin", "Brain", "Lung"], answer: 1 },
    { q: "Normal blood pH range?", options: ["6.8-7.0", "7.35-7.45", "7.5-8.0", "6.5-7.0"], answer: 1 },
    { q: "Which vitamin is produced by sunlight?", options: ["A", "B12", "C", "D"], answer: 3 },
    { q: "How many bones in an adult body?", options: ["206", "208", "210", "204"], answer: 0 },
    { q: "Insulin is produced by?", options: ["Liver", "Pancreas", "Kidney", "Thyroid"], answer: 1 },
  ],
  dental: [
    { q: "How many permanent teeth in adults?", options: ["28", "30", "32", "34"], answer: 2 },
    { q: "Hardest substance in the human body?", options: ["Bone", "Enamel", "Dentin", "Cartilage"], answer: 1 },
    { q: "Which tooth is also called the 'eye tooth'?", options: ["Incisor", "Canine", "Premolar", "Molar"], answer: 1 },
    { q: "Fluoride helps prevent?", options: ["Gum disease", "Tooth decay", "Bad breath", "Tooth loss"], answer: 1 },
    { q: "Primary teeth are also called?", options: ["Permanent", "Deciduous", "Wisdom", "Supernumerary"], answer: 1 },
  ],
  mba: [
    { q: "SWOT stands for Strengths, Weaknesses, Opportunities and?", options: ["Targets", "Threats", "Trends", "Tasks"], answer: 1 },
    { q: "ROI stands for?", options: ["Rate of Interest", "Return on Investment", "Revenue on Input", "Risk of Inflation"], answer: 1 },
    { q: "4 P's of Marketing include all EXCEPT?", options: ["Price", "Product", "People", "Place"], answer: 2 },
    { q: "Who wrote 'The Wealth of Nations'?", options: ["Keynes", "Adam Smith", "Marx", "Ricardo"], answer: 1 },
    { q: "Break-even point is when?", options: ["Profit > Loss", "Revenue = Cost", "Revenue > Cost", "Cost = 0"], answer: 1 },
  ],
  bed: [
    { q: "Bloom's Taxonomy is related to?", options: ["Finance", "Learning objectives", "Sports", "Medicine"], answer: 1 },
    { q: "Who proposed the theory of multiple intelligences?", options: ["Piaget", "Gardner", "Vygotsky", "Skinner"], answer: 1 },
    { q: "Formative assessment is done?", options: ["At the end", "During learning", "Before admission", "Never"], answer: 1 },
    { q: "ZPD concept was given by?", options: ["Piaget", "Bruner", "Vygotsky", "Dewey"], answer: 2 },
    { q: "NCF 2005 emphasizes?", options: ["Rote learning", "Activity-based learning", "Punishment", "Competition"], answer: 1 },
  ],
  arts: [
    { q: "Who painted the Mona Lisa?", options: ["Picasso", "Da Vinci", "Van Gogh", "Monet"], answer: 1 },
    { q: "GDP stands for?", options: ["Gross Domestic Product", "General Data Protocol", "Grand Development Plan", "Global Digital Platform"], answer: 0 },
    { q: "The Indus Valley Civilization is also known as?", options: ["Vedic", "Harappan", "Mauryan", "Gupta"], answer: 1 },
    { q: "Who is the father of Psychology?", options: ["Freud", "Wundt", "Jung", "Pavlov"], answer: 1 },
    { q: "Democracy means rule by the?", options: ["King", "Military", "People", "Religion"], answer: 2 },
  ],
  allied: [
    { q: "WBC stands for?", options: ["White Blood Cells", "Whole Body Count", "Water Based Chemical", "Wide Band Communication"], answer: 0 },
    { q: "Normal body temperature in °F?", options: ["96.8", "97.8", "98.6", "99.6"], answer: 2 },
    { q: "X-rays were discovered by?", options: ["Curie", "Röntgen", "Edison", "Tesla"], answer: 1 },
    { q: "Which blood group is universal donor?", options: ["A", "B", "AB", "O"], answer: 3 },
    { q: "Stethoscope was invented by?", options: ["Laennec", "Pasteur", "Fleming", "Lister"], answer: 0 },
  ],
};

// Map subjects to relevant audio types for sleep learning
export const subjectAudioMap: Record<string, string> = {
  // Calming subjects → Ocean/Rain
  "Alphabets (A-Z)": "lullaby",
  "Numbers (1-10)": "lullaby",
  "Colors & Shapes": "lullaby",
  "Rhymes & Songs": "lullaby",
  "Tamil Letters": "whisper",
  "English Words": "whisper",
  "Basic Math": "white-noise",
  "EVS Basics": "nature",
  "Tamil": "whisper",
  "English": "whisper",
  "Mathematics": "white-noise",
  "Maths": "white-noise",
  "Science": "nature",
  "Social Science": "ocean",
  "Tamil / English": "whisper",
  "Physics": "white-noise",
  "Chemistry": "rain",
  "Maths / Biology": "nature",
  "Computer Science": "white-noise",
  "Literature": "rain",
  "History": "ocean",
  "Economics": "white-noise",
  "Political Science": "ocean",
  "Psychology": "rain",
  "Engineering Maths": "white-noise",
  "Data Structures": "white-noise",
  "Thermodynamics": "wind",
  "Circuit Theory": "white-noise",
  "Programming": "white-noise",
  "Anatomy": "rain",
  "Physiology": "ocean",
  "Biochemistry": "rain",
  "Pharmacology": "rain",
  "Pathology": "rain",
  "Oral Anatomy": "rain",
  "Dental Materials": "white-noise",
  "Oral Pathology": "rain",
  "Prosthodontics": "white-noise",
  "Orthodontics": "white-noise",
  "Periodontics": "rain",
  "Endodontics": "rain",
  "Oral Surgery": "ocean",
  "Pedodontics": "lullaby",
  "Community Dentistry": "nature",
  "Oral Medicine & Radiology": "white-noise",
  "Conservative Dentistry": "rain",
  "Marketing": "ocean",
  "Finance": "white-noise",
  "HR Management": "rain",
  "Operations": "white-noise",
  "Business Strategy": "ocean",
  "Pedagogy": "rain",
  "Child Psychology": "nature",
  "Teaching Methods": "rain",
  "Classroom Mgmt": "white-noise",
  "Assessment": "white-noise",
  "Human Anatomy": "rain",
  "Microbiology": "rain",
  "Clinical Lab": "white-noise",
  "Radiology": "white-noise",
  "Nursing Care": "ocean",
};
