// Revision content (flashcard-style) for each subject
export interface RevisionItem {
  front: string;
  back: string;
}

// Fallback mapping: chapter name keywords → revisionBySubject key
const chapterFallbacks: Record<string, string> = {
  // Math chapters
  "Numbers": "Basic Math", "Addition": "Basic Math", "Subtraction": "Basic Math",
  "Shapes": "Colors & Shapes", "Patterns": "Basic Math",
  "Numbers & Operations": "Basic Math", "Fractions": "Mathematics", "Measurement": "Mathematics",
  "Geometry": "Mathematics", "Data Handling": "Mathematics", "Money": "Basic Math",
  "Time & Calendar": "Basic Math", "Number System": "Mathematics", "Algebra": "Mathematics",
  "Mensuration": "Mathematics", "Statistics": "Mathematics", "Ratio & Proportion": "Mathematics",
  "Profit & Loss": "Mathematics", "Simple Interest": "Mathematics",
  "Real Numbers": "Mathematics", "Polynomials": "Mathematics", "Linear Equations": "Mathematics",
  "Quadratic Equations": "Mathematics", "Coordinate Geometry": "Mathematics",
  "Trigonometry": "Maths", "Statistics & Probability": "Mathematics",
  "Circles": "Mathematics", "Surface Area & Volume": "Mathematics",
  "Sets & Functions": "Maths", "Calculus": "Maths", "Matrices & Determinants": "Maths",
  "Probability": "Maths", "Vectors": "Maths", "Differential Equations": "Maths",
  // Science chapters
  "Living & Non-living": "EVS Basics", "Plants": "EVS Basics", "Animals": "EVS Basics",
  "Our Body": "Science", "Water & Air": "EVS Basics", "Food & Nutrition": "Science",
  "Force & Motion": "Physics", "Heat & Temperature": "Physics", "Light": "Physics",
  "Electricity": "Physics", "Plant Kingdom": "Science", "Human Body Systems": "Science",
  "Acids & Bases": "Chemistry", "Laws of Motion": "Physics", "Atomic Structure": "Chemistry",
  "Chemical Reactions": "Chemistry", "Heredity & Evolution": "Science",
  "Optics": "Physics", "Electricity & Magnetism": "Physics", "Carbon Compounds": "Chemistry",
  "Reproduction": "Science",
  // Tamil chapters
  "Tamil Alphabets": "Tamil Letters", "Simple Words": "Tamil",
  "Sentences": "Tamil", "Poems": "Tamil", "Stories": "Tamil",
  "Prose": "Literature", "Poetry": "Literature", "Grammar": "English",
  "Comprehension": "English", "Letter Writing": "English", "Essay": "English",
  "Grammar - Phonetics": "Tamil", "Grammar - Syntax": "Tamil", "Literature": "Literature",
  "Essay & Letter": "English",
  // English chapters
  "Alphabets & Phonics": "English Words", "Reading Comprehension": "English",
  "Simple Grammar": "English", "Vocabulary": "English Words",
  "Stories & Poems": "Literature", "Writing Skills": "English",
  "Grammar & Usage": "English", "Writing": "English",
  // Social Science chapters
  "My Family": "Social Science", "My Neighbourhood": "Social Science",
  "Our Country India": "Social Science", "Festivals": "Social Science",
  "Maps & Directions": "Social Science",
  "History - Ancient India": "History", "History - Medieval India": "History",
  "Geography": "Social Science", "Civics": "Political Science",
  "Indian National Movement": "History", "World History": "History",
  "Indian Geography": "Social Science", "Indian Constitution": "Political Science",
  "Disaster Management": "Science",
  // EVS chapters
  "Plants Around Us": "EVS Basics", "Animals Around Us": "EVS Basics",
  "Weather & Seasons": "EVS Basics", "Clean Environment": "EVS Basics",
  "Our Helpers": "EVS Basics",
  // Physics 11-12
  "Kinematics": "Physics", "Work, Energy & Power": "Physics",
  "Gravitation": "Physics", "Waves": "Physics", "Electrostatics": "Physics",
  "Current Electricity": "Physics",
  // Chemistry 11-12
  "Chemical Bonding": "Chemistry", "Thermodynamics": "Thermodynamics",
  "Solutions": "Chemistry", "Organic Chemistry": "Chemistry", "Electrochemistry": "Chemistry",
  // Biology
  "Cell Biology": "Science", "Plant Biology": "Science",
  "Human Physiology": "Physiology", "Genetics": "Science", "Ecology": "Science",
  // Pre-school
  "Letters A-F": "Alphabets (A-Z)", "Letters G-L": "Alphabets (A-Z)",
  "Letters M-R": "Alphabets (A-Z)", "Letters S-Z": "Alphabets (A-Z)",
  "Numbers 1-5": "Numbers (1-10)", "Numbers 6-10": "Numbers (1-10)",
  "Numbers 11-20": "Numbers (1-10)",
  "Vowels (உயிர் எழுத்துக்கள்)": "Tamil Letters",
  "Consonants (மெய் எழுத்துக்கள்)": "Tamil Letters",
  "Primary Colors": "Colors & Shapes",
  "English Rhymes": "Rhymes & Songs", "Tamil Rhymes": "Rhymes & Songs",
  // Higher ed
  "Engineering Maths": "Engineering Maths", "Data Structures": "Data Structures",
  "Circuit Theory": "Circuit Theory", "Programming": "Programming",
};

export function getRevisionItems(subject: string): RevisionItem[] {
  // Exact match first
  if (revisionBySubject[subject] && revisionBySubject[subject].length > 0) {
    return revisionBySubject[subject];
  }
  // Fallback mapping
  const fallbackKey = chapterFallbacks[subject];
  if (fallbackKey && revisionBySubject[fallbackKey]) {
    return revisionBySubject[fallbackKey];
  }
  // Partial match: find any key that contains the subject name or vice versa
  const lowerSubject = subject.toLowerCase();
  for (const key of Object.keys(revisionBySubject)) {
    if (key.toLowerCase().includes(lowerSubject) || lowerSubject.includes(key.toLowerCase())) {
      return revisionBySubject[key];
    }
  }
  return [];
}

export const revisionBySubject: Record<string, RevisionItem[]> = {
  "Alphabets (A-Z)": [
    { front: "A", back: "🍎 Apple" }, { front: "B", back: "🏀 Ball" }, { front: "C", back: "🐱 Cat" },
    { front: "D", back: "🐶 Dog" }, { front: "E", back: "🐘 Elephant" }, { front: "F", back: "🐸 Frog" },
    { front: "G", back: "🍇 Grapes" }, { front: "H", back: "🏠 House" }, { front: "I", back: "🍦 Ice Cream" },
    { front: "J", back: "🤹 Juggler" }, { front: "K", back: "🪁 Kite" }, { front: "L", back: "🦁 Lion" },
    { front: "M", back: "🌙 Moon" }, { front: "N", back: "🥜 Nut" }, { front: "O", back: "🍊 Orange" },
    { front: "P", back: "🐧 Penguin" }, { front: "Q", back: "👸 Queen" }, { front: "R", back: "🌈 Rainbow" },
    { front: "S", back: "⭐ Star" }, { front: "T", back: "🌳 Tree" }, { front: "U", back: "☂️ Umbrella" },
    { front: "V", back: "🎻 Violin" }, { front: "W", back: "🐋 Whale" }, { front: "X", back: "🎄 Xmas Tree" },
    { front: "Y", back: "🧶 Yarn" }, { front: "Z", back: "🦓 Zebra" },
  ],
  "Numbers (1-10)": [
    { front: "1", back: "One ☝️" }, { front: "2", back: "Two ✌️" }, { front: "3", back: "Three 🤟" },
    { front: "4", back: "Four 🍀" }, { front: "5", back: "Five 🖐️" }, { front: "6", back: "Six 🎲" },
    { front: "7", back: "Seven 🌈" }, { front: "8", back: "Eight 🎱" }, { front: "9", back: "Nine 🎯" },
    { front: "10", back: "Ten 🔟" },
    { front: "What comes after 5?", back: "6" },
    { front: "What comes before 9?", back: "8" },
    { front: "3 + 4 = ?", back: "7" },
    { front: "10 - 3 = ?", back: "7" },
    { front: "Biggest single digit?", back: "9" },
  ],
  "Colors & Shapes": [
    { front: "🔴", back: "Red" }, { front: "🟢", back: "Green" }, { front: "🔵", back: "Blue" },
    { front: "🟡", back: "Yellow" }, { front: "🟠", back: "Orange" }, { front: "🟣", back: "Purple" },
    { front: "⬛", back: "Square – 4 equal sides" }, { front: "🔺", back: "Triangle – 3 sides" },
    { front: "⚪", back: "Circle – 0 corners, 0 sides" }, { front: "⬜", back: "Rectangle – 4 sides, opposite equal" },
    { front: "How many sides in a pentagon?", back: "5 sides" },
    { front: "How many sides in a hexagon?", back: "6 sides" },
    { front: "Primary colors", back: "Red, Blue, Yellow" },
    { front: "Red + Blue = ?", back: "Purple" },
    { front: "Red + Yellow = ?", back: "Orange" },
  ],
  "Rhymes & Songs": [
    { front: "Twinkle Twinkle", back: "Little Star ⭐" }, { front: "Jack and Jill", back: "Went up the hill 🏔️" },
    { front: "Baa Baa", back: "Black Sheep 🐑" }, { front: "Humpty Dumpty", back: "Sat on a wall 🧱" },
    { front: "Mary had a", back: "Little Lamb 🐑" }, { front: "Row Row Row", back: "Your Boat 🚣" },
    { front: "London Bridge is", back: "Falling Down 🌉" }, { front: "Old MacDonald had a", back: "Farm 🐄" },
    { front: "Itsy Bitsy", back: "Spider 🕷️" }, { front: "Rain Rain", back: "Go Away ☔" },
  ],
  "Tamil Letters": [
    { front: "அ", back: "First vowel (a)" }, { front: "ஆ", back: "Long A (aa)" },
    { front: "இ", back: "Short i" }, { front: "ஈ", back: "Long i (ii)" },
    { front: "உ", back: "Short u" }, { front: "ஊ", back: "Long u (uu)" },
    { front: "எ", back: "Short e" }, { front: "ஏ", back: "Long e (ee)" },
    { front: "ஐ", back: "ai" }, { front: "ஒ", back: "Short o" },
    { front: "ஓ", back: "Long o (oo)" }, { front: "ஔ", back: "au" },
    { front: "க", back: "First consonant (ka)" }, { front: "ங", back: "Nasal (nga)" },
    { front: "ச", back: "Sa/Cha sound" }, { front: "ந", back: "Dental na" },
    { front: "த", back: "Tha sound" }, { front: "ப", back: "Pa sound" },
    { front: "ம", back: "Ma sound" }, { front: "ய", back: "Ya sound" },
    { front: "How many vowels in Tamil?", back: "12" },
    { front: "How many consonants in Tamil?", back: "18" },
  ],
  "English Words": [
    { front: "Cat", back: "A small furry pet 🐱" }, { front: "Sun", back: "The star that gives light ☀️" },
    { front: "Book", back: "Pages with words 📖" }, { front: "Tree", back: "Tall plant with leaves 🌳" },
    { front: "Fish", back: "Lives in water 🐟" }, { front: "Bird", back: "Has wings and feathers 🐦" },
    { front: "Rain", back: "Water from clouds 🌧️" }, { front: "Star", back: "Shines at night ⭐" },
    { front: "Moon", back: "Seen at night 🌙" }, { front: "Flower", back: "Grows in garden 🌸" },
    { front: "River", back: "Flowing water 🏞️" }, { front: "Mountain", back: "Very tall land 🏔️" },
    { front: "Ocean", back: "Largest body of water 🌊" },
  ],
  "Basic Math": [
    { front: "5 + 3 = ?", back: "8" }, { front: "10 - 4 = ?", back: "6" },
    { front: "3 × 3 = ?", back: "9" }, { front: "12 ÷ 4 = ?", back: "3" },
    { front: "7 + 8 = ?", back: "15" }, { front: "20 - 13 = ?", back: "7" },
    { front: "6 × 7 = ?", back: "42" }, { front: "56 ÷ 8 = ?", back: "7" },
    { front: "What is even number?", back: "Divisible by 2 (2,4,6,8...)" },
    { front: "What is odd number?", back: "Not divisible by 2 (1,3,5,7...)" },
    { front: "100 - 45 = ?", back: "55" }, { front: "9 × 9 = ?", back: "81" },
    { front: "Place value of 5 in 356", back: "Tens (50)" },
    { front: "Smallest prime number", back: "2" },
    { front: "Sum of angles in triangle", back: "180°" },
  ],
  "EVS Basics": [
    { front: "What do plants need?", back: "Sunlight, Water, Air 🌱" },
    { front: "Which animal gives eggs?", back: "Hen 🐔" },
    { front: "3 states of water?", back: "Solid, Liquid, Gas 💧" },
    { front: "What do plants give us?", back: "Oxygen, Food, Shade" },
    { front: "Water cycle steps", back: "Evaporation → Condensation → Precipitation" },
    { front: "Parts of a plant", back: "Root, Stem, Leaf, Flower, Fruit" },
    { front: "What is photosynthesis?", back: "Plants make food using sunlight" },
    { front: "Which season is hottest?", back: "Summer ☀️" },
    { front: "What protects Earth from Sun?", back: "Atmosphere / Ozone layer" },
    { front: "Name 3 domestic animals", back: "Dog, Cow, Cat" },
    { front: "Name 3 wild animals", back: "Lion, Tiger, Elephant" },
    { front: "What is recycling?", back: "Reusing waste materials ♻️" },
  ],
  "Tamil": [
    { front: "நீர் = ?", back: "Water 💧" }, { front: "தீ = ?", back: "Fire 🔥" },
    { front: "காற்று = ?", back: "Wind 🌬️" }, { front: "மண் = ?", back: "Earth/Soil 🌍" },
    { front: "Thirukkural author?", back: "Thiruvalluvar" },
    { front: "வானம் = ?", back: "Sky" }, { front: "கடல் = ?", back: "Sea 🌊" },
    { front: "மலை = ?", back: "Mountain 🏔️" }, { front: "ஆறு = ?", back: "River 🏞️" },
    { front: "Number of Thirukkural chapters", back: "133" },
    { front: "Silapathikaram author", back: "Ilango Adigal" },
    { front: "Tholkappiyam is about", back: "Tamil grammar" },
    { front: "First Tamil Sangam location", back: "Then Madurai" },
    { front: "Bharathiyar famous poem", back: "Pudhumai Penn (Modern Woman)" },
    { front: "Tamil is how old?", back: "Over 2000 years, one of oldest living languages" },
  ],
  "English": [
    { front: "Noun", back: "Naming word (person, place, thing)" },
    { front: "Verb", back: "Action word (run, eat, write)" },
    { front: "Adjective", back: "Describing word (big, red, fast)" },
    { front: "Adverb", back: "Modifies verb (quickly, slowly)" },
    { front: "Pronoun", back: "Replaces noun (he, she, it, they)" },
    { front: "Preposition", back: "Shows position (in, on, at, under)" },
    { front: "Conjunction", back: "Joins words/sentences (and, but, or)" },
    { front: "Interjection", back: "Exclamation (Wow!, Oh!, Alas!)" },
    { front: "Simile uses", back: "'like' or 'as' for comparison" },
    { front: "Metaphor", back: "Direct comparison without like/as" },
    { front: "Alliteration", back: "Repeated initial consonant sounds" },
    { front: "Synonym", back: "Words with similar meaning" },
    { front: "Antonym", back: "Words with opposite meaning" },
    { front: "Tense types", back: "Past, Present, Future" },
    { front: "Active voice example", back: "She writes a letter" },
    { front: "Passive voice example", back: "A letter is written by her" },
  ],
  "Mathematics": [
    { front: "Area of Rectangle", back: "Length × Breadth" },
    { front: "Perimeter of Square", back: "4 × Side" },
    { front: "½ + ¼ = ?", back: "¾" },
    { front: "Volume of Cube", back: "Side³" },
    { front: "Area of Triangle", back: "½ × Base × Height" },
    { front: "Area of Circle", back: "πr²" },
    { front: "Circumference of Circle", back: "2πr" },
    { front: "Pythagorean theorem", back: "a² + b² = c²" },
    { front: "Volume of Cylinder", back: "πr²h" },
    { front: "Surface area of Sphere", back: "4πr²" },
    { front: "Sum of interior angles of polygon", back: "(n-2) × 180°" },
    { front: "Quadratic formula", back: "x = (-b ± √(b²-4ac)) / 2a" },
    { front: "Slope formula", back: "(y₂ - y₁) / (x₂ - x₁)" },
    { front: "Distance formula", back: "√((x₂-x₁)² + (y₂-y₁)²)" },
    { front: "HCF of 12 and 18", back: "6" },
    { front: "LCM of 4 and 6", back: "12" },
  ],
  "Maths": [
    { front: "√144 = ?", back: "12" }, { front: "LCM(4,6) = ?", back: "12" },
    { front: "π ≈ ?", back: "3.14159..." }, { front: "Area of Circle", back: "πr²" },
    { front: "sin 30° = ?", back: "0.5" }, { front: "cos 60° = ?", back: "0.5" },
    { front: "tan 45° = ?", back: "1" }, { front: "sin²θ + cos²θ = ?", back: "1" },
    { front: "log₁₀ 100 = ?", back: "2" }, { front: "2⁵ = ?", back: "32" },
    { front: "Sum of GP (infinite)", back: "a / (1-r), |r| < 1" },
    { front: "nCr formula", back: "n! / (r!(n-r)!)" },
    { front: "Derivative of xⁿ", back: "nxⁿ⁻¹" },
    { front: "∫xⁿ dx = ?", back: "xⁿ⁺¹/(n+1) + C" },
    { front: "Matrix determinant 2×2", back: "ad - bc" },
  ],
  "Science": [
    { front: "H₂O", back: "Water 💧" }, { front: "CO₂", back: "Carbon Dioxide" },
    { front: "Photosynthesis needs?", back: "Sunlight + CO₂ + H₂O" },
    { front: "Boiling point of water", back: "100°C" },
    { front: "Freezing point of water", back: "0°C" },
    { front: "Speed of light", back: "3 × 10⁸ m/s" },
    { front: "Speed of sound in air", back: "343 m/s" },
    { front: "Newton's 1st law", back: "Object at rest stays at rest" },
    { front: "Newton's 2nd law", back: "F = ma" },
    { front: "Newton's 3rd law", back: "Every action has equal opposite reaction" },
    { front: "Gravity on Earth", back: "9.8 m/s²" },
    { front: "Atomic number", back: "Number of protons" },
    { front: "Periodic table rows called", back: "Periods" },
    { front: "Periodic table columns called", back: "Groups" },
    { front: "pH scale range", back: "0-14" },
    { front: "Neutral pH", back: "7" },
    { front: "Mitochondria function", back: "Powerhouse of the cell" },
    { front: "Cell wall found in", back: "Plant cells (not animal)" },
  ],
  "Social Science": [
    { front: "Capital of India", back: "New Delhi 🇮🇳" }, { front: "Father of Nation", back: "Mahatma Gandhi" },
    { front: "Independence Day", back: "August 15, 1947" }, { front: "Republic Day", back: "January 26, 1950" },
    { front: "Largest state by area", back: "Rajasthan" },
    { front: "Longest river in India", back: "Ganga (2525 km)" },
    { front: "Highest peak in India", back: "Kangchenjunga (in India)" },
    { front: "Indian Constitution articles", back: "448 (originally 395)" },
    { front: "Fundamental Rights", back: "Part III of Constitution" },
    { front: "Right to Education Act", back: "2009" },
    { front: "Panchayati Raj started", back: "73rd Amendment, 1992" },
    { front: "First PM of India", back: "Jawaharlal Nehru" },
    { front: "Tropic of Cancer passes through", back: "8 Indian states" },
    { front: "India's largest desert", back: "Thar Desert" },
    { front: "Three branches of govt", back: "Legislature, Executive, Judiciary" },
  ],
  "Physics": [
    { front: "F = ?", back: "ma (Force = mass × acceleration)" },
    { front: "Speed of light", back: "3 × 10⁸ m/s" },
    { front: "V = IR", back: "Ohm's Law" },
    { front: "Unit of Power", back: "Watt (W)" },
    { front: "Unit of Energy", back: "Joule (J)" },
    { front: "E = mc²", back: "Einstein's mass-energy equivalence" },
    { front: "KE formula", back: "½mv²" },
    { front: "PE formula", back: "mgh" },
    { front: "Coulomb's Law", back: "F = kq₁q₂/r²" },
    { front: "Snell's Law", back: "n₁sinθ₁ = n₂sinθ₂" },
    { front: "Electromagnetic spectrum order", back: "Radio, Micro, IR, Visible, UV, X-ray, Gamma" },
    { front: "Unit of frequency", back: "Hertz (Hz)" },
    { front: "Capacitance unit", back: "Farad (F)" },
    { front: "Inductance unit", back: "Henry (H)" },
    { front: "Planck's constant", back: "6.626 × 10⁻³⁴ J·s" },
  ],
  "Chemistry": [
    { front: "pH of water", back: "7 (neutral)" },
    { front: "NaCl", back: "Sodium Chloride (table salt)" },
    { front: "Atomic no. of Gold", back: "79 (Au)" },
    { front: "Noble gas group", back: "Group 18" },
    { front: "Avogadro's number", back: "6.022 × 10²³" },
    { front: "Ideal gas law", back: "PV = nRT" },
    { front: "Mole concept", back: "1 mole = 6.022 × 10²³ particles" },
    { front: "Atomic number of Carbon", back: "6" },
    { front: "Atomic number of Oxygen", back: "8" },
    { front: "Electronegativity trend", back: "Increases left to right, bottom to top" },
    { front: "Ionic bond", back: "Transfer of electrons" },
    { front: "Covalent bond", back: "Sharing of electrons" },
    { front: "Oxidation", back: "Loss of electrons" },
    { front: "Reduction", back: "Gain of electrons" },
    { front: "Molarity formula", back: "Moles of solute / Liters of solution" },
  ],
  "Tamil / English": [
    { front: "Bharathiyar", back: "Tamil National Poet, wrote about freedom & women's rights 🇮🇳" },
    { front: "Bharathidasan", back: "Paavendar (King of Poetry), disciple of Bharathiyar" },
    { front: "Shakespeare", back: "Born 1564, greatest English playwright" },
    { front: "Kambar", back: "Wrote Kamba Ramayanam in Tamil" },
    { front: "Thiruvalluvar lived in", back: "Mylapore, Chennai (believed)" },
    { front: "Wordsworth known for", back: "Romantic poetry, nature poems" },
    { front: "Tamil Sangam literature age", back: "300 BCE – 300 CE" },
    { front: "Parts of speech in English", back: "8 (Noun, Verb, Adj, Adv, Pronoun, Prep, Conj, Interj)" },
    { front: "Tamil literature periods", back: "Sangam, Post-Sangam, Medieval, Modern" },
    { front: "Figure of speech: Irony", back: "Meaning opposite of literal words" },
  ],
  "Maths / Biology": [
    { front: "d/dx sin(x)", back: "cos(x)" },
    { front: "DNA full form", back: "Deoxyribonucleic Acid" },
    { front: "Mitochondria", back: "Powerhouse of the cell" },
    { front: "RNA full form", back: "Ribonucleic Acid" },
    { front: "d/dx cos(x)", back: "-sin(x)" },
    { front: "∫sin(x)dx", back: "-cos(x) + C" },
    { front: "Cell division types", back: "Mitosis and Meiosis" },
    { front: "Chromosomes in human", back: "46 (23 pairs)" },
    { front: "Blood groups", back: "A, B, AB, O" },
    { front: "Universal donor", back: "O negative" },
    { front: "Universal recipient", back: "AB positive" },
    { front: "Photosynthesis equation", back: "6CO₂ + 6H₂O → C₆H₁₂O₆ + 6O₂" },
    { front: "Krebs cycle location", back: "Mitochondrial matrix" },
    { front: "Hardy-Weinberg principle", back: "p² + 2pq + q² = 1" },
  ],
  "Computer Science": [
    { front: "1 byte = ?", back: "8 bits" }, { front: "RAM", back: "Random Access Memory" },
    { front: "CPU", back: "Central Processing Unit" }, { front: "Binary of 10", back: "1010" },
    { front: "1 KB = ?", back: "1024 bytes" }, { front: "1 MB = ?", back: "1024 KB" },
    { front: "HTTP stands for", back: "HyperText Transfer Protocol" },
    { front: "HTML stands for", back: "HyperText Markup Language" },
    { front: "IP address", back: "Unique identifier for network devices" },
    { front: "Boolean values", back: "True and False" },
    { front: "Primary key", back: "Unique identifier in database table" },
    { front: "SQL stands for", back: "Structured Query Language" },
    { front: "Algorithm", back: "Step-by-step procedure to solve a problem" },
    { front: "Compiler vs Interpreter", back: "Compiler: whole code at once; Interpreter: line by line" },
    { front: "Cache memory", back: "Fast, small memory between CPU and RAM" },
  ],
  "Engineering Maths": [
    { front: "L{1} = ?", back: "1/s" }, { front: "Eigenvalue of I", back: "1" },
    { front: "∇ operator", back: "Del (gradient)" }, { front: "Rank of I₃", back: "3" },
    { front: "L{eᵃᵗ} = ?", back: "1/(s-a)" },
    { front: "Fourier series period", back: "2L or 2π" },
    { front: "Cauchy-Riemann equations", back: "∂u/∂x = ∂v/∂y, ∂u/∂y = -∂v/∂x" },
    { front: "Taylor series center", back: "Expansion around a point 'a'" },
    { front: "Divergence theorem", back: "Converts volume integral to surface integral" },
    { front: "Stokes' theorem", back: "Relates surface integral to line integral" },
    { front: "Characteristic equation", back: "|A - λI| = 0" },
    { front: "L{sin(at)}", back: "a/(s² + a²)" },
    { front: "Partial differential equation", back: "Involves partial derivatives of multiple variables" },
  ],
  "Data Structures": [
    { front: "Stack", back: "LIFO (Last In First Out)" }, { front: "Queue", back: "FIFO (First In First Out)" },
    { front: "Binary Search O(?)", back: "O(log n)" }, { front: "Binary Tree max children", back: "2" },
    { front: "Linked List advantage", back: "Dynamic size, easy insert/delete" },
    { front: "Array advantage", back: "O(1) random access" },
    { front: "Hash Table average lookup", back: "O(1)" },
    { front: "BFS uses", back: "Queue" },
    { front: "DFS uses", back: "Stack (or recursion)" },
    { front: "Heap property (min)", back: "Parent ≤ Children" },
    { front: "AVL Tree", back: "Self-balancing BST" },
    { front: "Bubble Sort O(?)", back: "O(n²)" },
    { front: "Merge Sort O(?)", back: "O(n log n)" },
    { front: "Quick Sort average O(?)", back: "O(n log n)" },
    { front: "Graph traversal types", back: "BFS and DFS" },
  ],
  "Thermodynamics": [
    { front: "1st Law", back: "Energy conservation (ΔU = Q - W)" },
    { front: "Absolute Zero", back: "-273.15°C (0 K)" },
    { front: "Entropy unit", back: "J/K" }, { front: "Carnot depends on", back: "Temperature ratio" },
    { front: "2nd Law", back: "Entropy of isolated system always increases" },
    { front: "3rd Law", back: "Entropy approaches 0 as T approaches 0K" },
    { front: "Enthalpy", back: "H = U + PV" },
    { front: "Gibbs free energy", back: "G = H - TS" },
    { front: "Isothermal process", back: "Constant temperature" },
    { front: "Adiabatic process", back: "No heat exchange" },
    { front: "Isobaric process", back: "Constant pressure" },
    { front: "Isochoric process", back: "Constant volume" },
    { front: "Carnot efficiency", back: "1 - Tc/Th" },
  ],
  "Circuit Theory": [
    { front: "KCL", back: "Sum of currents at node = 0" }, { front: "Capacitance unit", back: "Farad" },
    { front: "AC freq in India", back: "50 Hz" }, { front: "Impedance unit", back: "Ohm" },
    { front: "KVL", back: "Sum of voltages in loop = 0" },
    { front: "Resistors in series", back: "R_total = R₁ + R₂ + ..." },
    { front: "Resistors in parallel", back: "1/R_total = 1/R₁ + 1/R₂ + ..." },
    { front: "Power formula", back: "P = VI = I²R = V²/R" },
    { front: "Thevenin's theorem", back: "Any circuit = Vth + Rth in series" },
    { front: "Norton's theorem", back: "Any circuit = In || Rn" },
    { front: "Time constant RC", back: "τ = RC" },
    { front: "Resonant frequency", back: "f = 1/(2π√LC)" },
    { front: "Transformer ratio", back: "V₁/V₂ = N₁/N₂" },
  ],
  "Programming": [
    { front: "OOP Pillars", back: "Encapsulation, Inheritance, Polymorphism, Abstraction" },
    { front: "Python typing", back: "Dynamically typed" },
    { front: "SQL", back: "Structured Query Language" },
    { front: "for loop purpose", back: "Repeat code a known number of times" },
    { front: "while loop purpose", back: "Repeat code while condition is true" },
    { front: "Function", back: "Reusable block of code" },
    { front: "Variable", back: "Named storage for data" },
    { front: "Array vs List", back: "Array: fixed type; List: dynamic in Python" },
    { front: "Recursion", back: "Function calling itself" },
    { front: "API stands for", back: "Application Programming Interface" },
    { front: "Git", back: "Version control system" },
    { front: "IDE stands for", back: "Integrated Development Environment" },
    { front: "Debugging", back: "Finding and fixing errors in code" },
    { front: "Exception handling", back: "try-catch/except blocks" },
  ],
  "Anatomy": [
    { front: "Bones in adult", back: "206" }, { front: "Largest bone", back: "Femur" },
    { front: "Smallest bone", back: "Stapes (ear)" }, { front: "Largest organ", back: "Skin" },
    { front: "Muscles in body", back: "~600" },
    { front: "Largest muscle", back: "Gluteus Maximus" },
    { front: "Smallest muscle", back: "Stapedius (ear)" },
    { front: "Cranial nerves count", back: "12 pairs" },
    { front: "Spinal nerves count", back: "31 pairs" },
    { front: "Vertebrae count", back: "33 (7C, 12T, 5L, 5S, 4Co)" },
    { front: "Heart chambers", back: "4 (2 atria, 2 ventricles)" },
    { front: "Lungs lobes", back: "Right: 3, Left: 2" },
    { front: "Brain parts", back: "Cerebrum, Cerebellum, Brainstem" },
    { front: "Largest artery", back: "Aorta" },
    { front: "Blood types", back: "A, B, AB, O (+ or -)" },
  ],
  "Physiology": [
    { front: "Normal BP", back: "120/80 mmHg" }, { front: "Heart rate", back: "60-100 bpm" },
    { front: "RBC lifespan", back: "120 days" }, { front: "Pacemaker", back: "SA Node" },
    { front: "Tidal volume", back: "~500 mL" },
    { front: "Normal body temp", back: "37°C / 98.6°F" },
    { front: "GFR (Glomerular filtration rate)", back: "~125 mL/min" },
    { front: "Cardiac output", back: "~5 L/min" },
    { front: "WBC count normal", back: "4000-11000/µL" },
    { front: "Platelet count normal", back: "1.5-4 lakh/µL" },
    { front: "Hemoglobin normal (male)", back: "14-18 g/dL" },
    { front: "Insulin produced by", back: "Beta cells of pancreas" },
    { front: "Thyroid hormone", back: "T3 and T4" },
    { front: "ADH function", back: "Water reabsorption in kidneys" },
  ],
  "Biochemistry": [
    { front: "ATP", back: "Adenosine Triphosphate" }, { front: "Krebs cycle location", back: "Mitochondria" },
    { front: "Amylase digests", back: "Starch" }, { front: "Cholesterol is a", back: "Lipid" },
    { front: "Glycolysis location", back: "Cytoplasm" },
    { front: "Glycolysis net ATP", back: "2 ATP" },
    { front: "Krebs cycle net ATP", back: "2 ATP (per glucose)" },
    { front: "ETC produces", back: "~34 ATP" },
    { front: "Amino acids total", back: "20 standard" },
    { front: "Essential amino acids", back: "9 (cannot be synthesized)" },
    { front: "Enzyme suffix", back: "-ase" },
    { front: "Lipase digests", back: "Fats/Lipids" },
    { front: "Pepsin digests", back: "Proteins" },
    { front: "DNA bases", back: "A, T, G, C" },
    { front: "RNA bases", back: "A, U, G, C" },
  ],
  "Pharmacology": [
    { front: "Aspirin class", back: "NSAID" }, { front: "Paracetamol =", back: "Acetaminophen" },
    { front: "Penicillin discoverer", back: "Alexander Fleming" }, { front: "IV route", back: "Into vein" },
    { front: "IM route", back: "Into muscle" },
    { front: "SC route", back: "Subcutaneous (under skin)" },
    { front: "Half-life definition", back: "Time for drug concentration to reduce by half" },
    { front: "Bioavailability of IV", back: "100%" },
    { front: "Agonist", back: "Activates receptor" },
    { front: "Antagonist", back: "Blocks receptor" },
    { front: "First-pass metabolism", back: "Drug metabolized by liver before systemic circulation" },
    { front: "Therapeutic index", back: "TD50/ED50 — safety margin" },
    { front: "Adrenaline = ?", back: "Epinephrine" },
    { front: "Antibiotic mechanism (penicillin)", back: "Inhibits cell wall synthesis" },
  ],
  "Pathology": [
    { front: "Carcinoma origin", back: "Epithelial tissue" }, { front: "CRP indicates", back: "Inflammation" },
    { front: "Anemia = low", back: "Hemoglobin" }, { front: "Biopsy", back: "Tissue examination" },
    { front: "Sarcoma origin", back: "Connective tissue" },
    { front: "Leukemia", back: "Blood cancer" },
    { front: "Lymphoma", back: "Lymphatic system cancer" },
    { front: "Thrombosis", back: "Blood clot in vessel" },
    { front: "Embolism", back: "Traveling clot blocking vessel" },
    { front: "Necrosis", back: "Cell death in living tissue" },
    { front: "Apoptosis", back: "Programmed cell death" },
    { front: "Metaplasia", back: "One cell type replaced by another" },
    { front: "Dysplasia", back: "Abnormal cell growth" },
    { front: "Hyperplasia", back: "Increase in cell number" },
  ],
  "Oral Anatomy": [
    { front: "Permanent teeth", back: "32" }, { front: "Hardest substance", back: "Enamel" },
    { front: "Primary teeth", back: "20" }, { front: "TMJ", back: "Temporo Mandibular Joint" },
    { front: "Dental formula (permanent)", back: "2-1-2-3 / 2-1-2-3" },
    { front: "Dental formula (primary)", back: "2-1-0-2 / 2-1-0-2" },
    { front: "Tooth layers", back: "Enamel, Dentin, Cementum, Pulp" },
    { front: "Largest tooth", back: "First molar" },
    { front: "Smallest permanent tooth", back: "Mandibular central incisor" },
    { front: "Wisdom teeth number", back: "Third molars (4)" },
    { front: "First permanent tooth to erupt", back: "First molar (6 years)" },
    { front: "Tongue muscles", back: "4 intrinsic + 4 extrinsic" },
    { front: "Salivary glands", back: "Parotid, Submandibular, Sublingual" },
  ],
  "Dental Materials": [
    { front: "Amalgam contains", back: "Mercury" }, { front: "GIC", back: "Glass Ionomer Cement" },
    { front: "Impression material", back: "Alginate" }, { front: "Plaster setting", back: "Exothermic" },
    { front: "Composite resin", back: "Tooth-colored restorative" },
    { front: "Zinc phosphate cement", back: "Oldest luting cement" },
    { front: "Gold alloy type", back: "Type I (soft) to Type IV (extra hard)" },
    { front: "Wax types in dentistry", back: "Pattern, Processing, Impression" },
    { front: "Porcelain firing temp", back: "~900-1300°C" },
    { front: "Elastomeric impression", back: "Polysiloxane (PVS)" },
    { front: "Investment material", back: "For casting metal frameworks" },
    { front: "Biocompatibility", back: "Material doesn't harm body tissues" },
  ],
  "Oral Pathology": [
    { front: "Leukoplakia", back: "White lesion on mucosa" }, { front: "Caries cause", back: "Bacteria (S. mutans)" },
    { front: "Most common oral cancer", back: "SCC (Squamous Cell Carcinoma)" },
    { front: "Ameloblastoma origin", back: "Enamel organ" },
    { front: "Erythroplakia", back: "Red patch, high malignancy risk" },
    { front: "Lichen planus pattern", back: "Wickham's striae" },
    { front: "Odontogenic keratocyst", back: "Keratinizing cyst, high recurrence" },
    { front: "Periapical cyst", back: "Most common odontogenic cyst" },
    { front: "Ranula", back: "Floor of mouth mucocele" },
    { front: "Pemphigus", back: "Autoimmune blistering disease" },
    { front: "Fordyce granules", back: "Ectopic sebaceous glands, normal variant" },
    { front: "Epulis", back: "Growth on gingiva" },
  ],
  "Prosthodontics": [
    { front: "RPD", back: "Removable Partial Denture" }, { front: "Overjet", back: "Horizontal overlap" },
    { front: "Occlusal rim material", back: "Wax" }, { front: "Complete denture", back: "Replaces all teeth" },
    { front: "Kennedy Classification", back: "Classes I-IV for partially edentulous arches" },
    { front: "Overbite", back: "Vertical overlap of incisors" },
    { front: "Impression tray types", back: "Stock, Custom, Special" },
    { front: "Denture base material", back: "Acrylic resin (PMMA)" },
    { front: "Jaw relation record", back: "Maxillomandibular relationship" },
    { front: "Facebow purpose", back: "Transfer maxillary cast to articulator" },
    { front: "Implant material", back: "Titanium" },
    { front: "Porcelain-fused-to-metal", back: "PFM crown" },
  ],
  "Orthodontics": [
    { front: "Angle classification", back: "Malocclusion types I, II, III" },
    { front: "Cephalometry", back: "Skull measurement via X-ray" },
    { front: "NiTi wire", back: "Superelastic, shape memory" },
    { front: "Ideal overbite", back: "2-3mm" },
    { front: "Ideal overjet", back: "2-3mm" },
    { front: "Class I molar relation", back: "MB cusp of upper 6 in buccal groove of lower 6" },
    { front: "Headgear type", back: "Cervical pull, High pull, Combination" },
    { front: "Retainer purpose", back: "Maintain teeth position after treatment" },
    { front: "Functional appliance", back: "Modifies growth (e.g., Twin Block)" },
    { front: "Space maintainer", back: "Prevents space closure after early tooth loss" },
    { front: "Bracket types", back: "Metal, Ceramic, Self-ligating" },
    { front: "Anchorage", back: "Resistance to unwanted tooth movement" },
  ],
  "Periodontics": [
    { front: "Gingivitis", back: "Gum inflammation (reversible)" },
    { front: "Scaling removes", back: "Calculus/tartar" },
    { front: "Normal probing", back: "1-3mm" }, { front: "BOP", back: "Bleeding on Probing" },
    { front: "Periodontitis", back: "Bone loss + attachment loss" },
    { front: "Plaque", back: "Bacterial biofilm on teeth" },
    { front: "Calculus", back: "Mineralized plaque" },
    { front: "Periodontal ligament", back: "Connects tooth to alveolar bone" },
    { front: "Furcation involvement", back: "Bone loss between roots of multi-rooted teeth" },
    { front: "Guided tissue regeneration", back: "GTR — membrane-guided bone/tissue regrowth" },
    { front: "Mobility grading", back: "Grade I, II, III" },
    { front: "Flap surgery purpose", back: "Access for deep cleaning and bone grafting" },
  ],
  "Endodontics": [
    { front: "Root canal treats", back: "Infected/inflamed pulp" },
    { front: "Gutta percha", back: "Canal filling material" },
    { front: "NaOCl", back: "Root canal irrigant (sodium hypochlorite)" },
    { front: "Apex locator", back: "Electronic device to measure working length" },
    { front: "Pulpitis types", back: "Reversible and Irreversible" },
    { front: "Obturation", back: "Filling the root canal" },
    { front: "Access cavity shape (molar)", back: "Triangular (upper), Rectangular (lower)" },
    { front: "Barbed broach", back: "Pulp extirpation instrument" },
    { front: "EDTA purpose", back: "Chelating agent, removes smear layer" },
    { front: "Vital pulp therapy", back: "Pulp capping (direct/indirect)" },
    { front: "Periapical abscess", back: "Infection at root tip" },
    { front: "MTA", back: "Mineral Trioxide Aggregate — biocompatible material" },
  ],
  "Oral Surgery": [
    { front: "Forceps for", back: "Tooth extraction" },
    { front: "Local anesthetic", back: "Lidocaine 2% with adrenaline" },
    { front: "Impacted tooth", back: "Tooth unable to erupt fully" },
    { front: "Dry socket", back: "Alveolar osteitis — painful healing complication" },
    { front: "Elevator purpose", back: "Luxate tooth before extraction" },
    { front: "Suture material types", back: "Absorbable and Non-absorbable" },
    { front: "Le Fort fractures", back: "Types I, II, III of midface fractures" },
    { front: "Mandible fracture sites", back: "Condyle, Angle, Body, Symphysis" },
    { front: "Trismus", back: "Restricted mouth opening" },
    { front: "Biopsy types", back: "Incisional, Excisional, FNAC" },
    { front: "Cyst enucleation", back: "Complete surgical removal of cyst" },
    { front: "Nerve block", back: "Inferior Alveolar Nerve Block (IANB)" },
  ],
  "Pedodontics": [
    { front: "First tooth erupts", back: "~6 months (lower central incisor)" },
    { front: "Natal teeth", back: "Present at birth" },
    { front: "Pulpotomy", back: "Remove coronal pulp, preserve radicular" },
    { front: "Fluoride varnish", back: "Topical fluoride for caries prevention" },
    { front: "Space maintainer types", back: "Band & loop, Lingual arch, Nance, TPA" },
    { front: "Stainless steel crown", back: "Full coverage for primary molars" },
    { front: "Behavior management", back: "Tell-Show-Do technique" },
    { front: "Pit & fissure sealant", back: "Prevents occlusal caries" },
    { front: "Mixed dentition period", back: "6-12 years" },
    { front: "Neonatal teeth", back: "Erupt within first month" },
    { front: "Frankl behavior scale", back: "Definitely negative to Definitely positive" },
    { front: "Pulpectomy", back: "Complete pulp removal in primary teeth" },
  ],
  "Community Dentistry": [
    { front: "DMFT", back: "Decayed Missing Filled Teeth index" },
    { front: "OHI-S", back: "Simplified Oral Hygiene Index" },
    { front: "Primary prevention", back: "Fluoridation, sealants, education" },
    { front: "WHO", back: "World Health Organization" },
    { front: "Fluoride in water (optimal)", back: "0.7-1.2 ppm" },
    { front: "Levels of prevention", back: "Primary, Secondary, Tertiary" },
    { front: "Epidemiology", back: "Study of disease distribution in populations" },
    { front: "Prevalence", back: "Total cases at a point in time" },
    { front: "Incidence", back: "New cases in a time period" },
    { front: "Dean's Index measures", back: "Dental fluorosis" },
    { front: "Community periodontal index", back: "CPI — periodontal status assessment" },
    { front: "Atraumatic Restorative Treatment", back: "ART — hand instruments only, no anesthesia" },
  ],
  "Oral Medicine & Radiology": [
    { front: "OPG shows", back: "Full jaw panoramic view" },
    { front: "IOPA", back: "Intraoral Periapical radiograph" },
    { front: "Radiolucent =", back: "Dark on X-ray (less dense)" },
    { front: "CBCT", back: "Cone Beam Computed Tomography" },
    { front: "Radiopaque =", back: "White on X-ray (more dense)" },
    { front: "Bisecting angle technique", back: "IOPA technique for periapical view" },
    { front: "Paralleling technique", back: "More accurate IOPA technique" },
    { front: "Occlusal radiograph", back: "Shows floor of mouth / palate" },
    { front: "Contrast media", back: "Barium, Iodine — enhance imaging" },
    { front: "ALARA principle", back: "As Low As Reasonably Achievable (radiation)" },
    { front: "kVp controls", back: "Contrast and penetrating power" },
    { front: "mA controls", back: "Density (amount of radiation)" },
  ],
  "Conservative Dentistry": [
    { front: "Composite resin", back: "Tooth-colored filling material" },
    { front: "Black's classification", back: "6 classes of cavities (I-VI)" },
    { front: "Etching acid", back: "37% Phosphoric acid" },
    { front: "Class I cavity", back: "Pits and fissures of occlusal surface" },
    { front: "Class II cavity", back: "Proximal surfaces of premolars/molars" },
    { front: "Class III cavity", back: "Proximal surfaces of anteriors (no incisal)" },
    { front: "Class IV cavity", back: "Proximal + incisal edge of anteriors" },
    { front: "Class V cavity", back: "Gingival third of all teeth" },
    { front: "Bonding agent purpose", back: "Adhesion between tooth and restoration" },
    { front: "Indirect pulp capping", back: "Leave thin dentin over pulp, place Ca(OH)₂" },
    { front: "Rubber dam purpose", back: "Isolation during treatment" },
    { front: "Lining material", back: "Ca(OH)₂ — protects pulp" },
  ],
  "Marketing": [
    { front: "4 P's", back: "Product, Price, Place, Promotion" },
    { front: "USP", back: "Unique Selling Proposition" },
    { front: "AIDA model", back: "Attention, Interest, Desire, Action" },
    { front: "B2C", back: "Business to Customer" },
    { front: "B2B", back: "Business to Business" },
    { front: "Market segmentation", back: "Dividing market into distinct groups" },
    { front: "Target market", back: "Specific group a company aims to serve" },
    { front: "Brand equity", back: "Value derived from brand recognition" },
    { front: "SWOT in marketing", back: "Strengths, Weaknesses, Opportunities, Threats" },
    { front: "Digital marketing channels", back: "SEO, SEM, Social Media, Email, Content" },
    { front: "CRM stands for", back: "Customer Relationship Management" },
    { front: "Market penetration", back: "Existing product in existing market" },
  ],
  "Finance": [
    { front: "ROI", back: "Return on Investment" }, { front: "NPV", back: "Net Present Value" },
    { front: "Bull market", back: "Rising prices 📈" }, { front: "P/E ratio", back: "Price to Earnings ratio" },
    { front: "Balance sheet", back: "Assets = Liabilities + Equity" },
    { front: "Income statement", back: "Revenue - Expenses = Profit" },
    { front: "Cash flow types", back: "Operating, Investing, Financing" },
    { front: "IRR", back: "Internal Rate of Return" },
    { front: "Bear market", back: "Declining prices 📉" },
    { front: "Diversification", back: "Spreading investments to reduce risk" },
    { front: "Depreciation", back: "Decrease in asset value over time" },
    { front: "Working capital", back: "Current Assets - Current Liabilities" },
    { front: "EBITDA", back: "Earnings Before Interest, Taxes, Depreciation, Amortization" },
  ],
  "HR Management": [
    { front: "KPI", back: "Key Performance Indicator" }, { front: "360° feedback", back: "Feedback from all levels" },
    { front: "Maslow's top", back: "Self-actualization" }, { front: "Attrition", back: "Employee turnover/leaving" },
    { front: "Recruitment vs Selection", back: "Attract candidates vs Choose best candidate" },
    { front: "Job description", back: "Duties, responsibilities, requirements of a role" },
    { front: "Onboarding", back: "Process of integrating new employees" },
    { front: "Herzberg's theory", back: "Hygiene factors + Motivators" },
    { front: "McGregor Theory X", back: "Workers are lazy, need supervision" },
    { front: "McGregor Theory Y", back: "Workers are self-motivated" },
    { front: "HRIS", back: "Human Resource Information System" },
    { front: "Compensation types", back: "Direct (salary) + Indirect (benefits)" },
  ],
  "Operations": [
    { front: "JIT", back: "Just in Time — minimize inventory" },
    { front: "Six Sigma", back: "3.4 defects per million — near zero defects" },
    { front: "Lean", back: "Eliminate waste, maximize value" },
    { front: "FIFO", back: "First In First Out" },
    { front: "Supply chain", back: "Raw materials → Production → Distribution → Customer" },
    { front: "EOQ", back: "Economic Order Quantity" },
    { front: "Bottleneck", back: "Process step that limits throughput" },
    { front: "Kanban", back: "Visual workflow management system" },
    { front: "Quality control", back: "Inspection and testing of products" },
    { front: "Capacity planning", back: "Matching production capability to demand" },
    { front: "PDCA cycle", back: "Plan, Do, Check, Act" },
    { front: "5S methodology", back: "Sort, Set, Shine, Standardize, Sustain" },
  ],
  "Business Strategy": [
    { front: "SWOT: T", back: "Threats" }, { front: "Porter's forces", back: "5 competitive forces" },
    { front: "BCG quadrants", back: "Star, Cash Cow, Question Mark, Dog" },
    { front: "Blue ocean", back: "Create new uncontested market space" },
    { front: "Red ocean", back: "Compete in existing market" },
    { front: "Core competency", back: "Unique strength/capability of a firm" },
    { front: "Vertical integration", back: "Owning supply chain stages" },
    { front: "Horizontal integration", back: "Acquiring competitors" },
    { front: "First-mover advantage", back: "Benefits of entering market first" },
    { front: "Franchise model", back: "License brand/process to third party" },
    { front: "PESTEL analysis", back: "Political, Economic, Social, Tech, Environment, Legal" },
    { front: "Ansoff Matrix", back: "Market penetration, Development, Product dev, Diversification" },
  ],
  "Pedagogy": [
    { front: "Bloom's Taxonomy", back: "Remember, Understand, Apply, Analyze, Evaluate, Create" },
    { front: "Scaffolding by", back: "Bruner — gradual support reduction" },
    { front: "NCF 2005", back: "Activity-based, child-centered learning" },
    { front: "Constructivism", back: "Learners construct knowledge through experience" },
    { front: "Zone of Proximal Development", back: "Gap between what learner can do alone vs with help" },
    { front: "Formative assessment", back: "Ongoing assessment during learning" },
    { front: "Summative assessment", back: "End-of-unit/term evaluation" },
    { front: "Cooperative learning", back: "Students work in small groups" },
    { front: "Differentiated instruction", back: "Adapting teaching to diverse learners" },
    { front: "Inquiry-based learning", back: "Students explore questions and problems" },
    { front: "Multiple Intelligences", back: "Gardner — 8 types of intelligence" },
    { front: "Learning styles", back: "Visual, Auditory, Kinesthetic (VAK)" },
  ],
  "Child Psychology": [
    { front: "Piaget stages", back: "4: Sensorimotor, Preoperational, Concrete, Formal" },
    { front: "ZPD by", back: "Vygotsky" },
    { front: "Multiple Intelligences", back: "Howard Gardner — 8 types" },
    { front: "Erikson stages", back: "8 psychosocial stages across lifespan" },
    { front: "Attachment theory", back: "John Bowlby — early bonds affect development" },
    { front: "Nature vs Nurture", back: "Genetics vs Environment debate" },
    { front: "Kohlberg's theory", back: "Moral development in 3 levels, 6 stages" },
    { front: "Operant conditioning", back: "B.F. Skinner — reinforcement/punishment" },
    { front: "Classical conditioning", back: "Pavlov — stimulus-response association" },
    { front: "Schema", back: "Mental framework for understanding the world" },
    { front: "Assimilation", back: "Fitting new info into existing schema" },
    { front: "Accommodation", back: "Modifying schema for new info" },
    { front: "Concrete operational stage", back: "Age 7-11: logical thinking about concrete objects" },
  ],
  "Teaching Methods": [
    { front: "Project method by", back: "Kilpatrick" }, { front: "Socratic method", back: "Teaching through questioning" },
    { front: "Micro-teaching", back: "5-10 minute focused practice" },
    { front: "Formative assessment", back: "Assessment during learning process" },
    { front: "Lecture method", back: "Teacher-centered, one-way communication" },
    { front: "Discussion method", back: "Interactive exchange of ideas" },
    { front: "Demonstration method", back: "Teacher shows, students observe" },
    { front: "Flipped classroom", back: "Learn at home, practice in class" },
    { front: "Brainstorming", back: "Free idea generation without judgment" },
    { front: "Case study method", back: "Analyze real-world scenarios" },
    { front: "Role playing", back: "Act out scenarios to understand concepts" },
    { front: "Problem-based learning", back: "Learn through solving real problems" },
    { front: "Peer teaching", back: "Students teach each other" },
  ],
  "Classroom Mgmt": [
    { front: "Goal", back: "Create positive, productive learning environment" },
    { front: "Positive reinforcement", back: "Reward desired behavior 🎁" },
    { front: "Inclusive education", back: "All learners included regardless of ability" },
    { front: "Seating arrangement types", back: "Rows, U-shape, Clusters, Circle" },
    { front: "Time management", back: "Allocating time effectively across activities" },
    { front: "Classroom rules purpose", back: "Establish expectations and boundaries" },
    { front: "Proactive management", back: "Prevent issues before they occur" },
    { front: "Reactive management", back: "Respond to issues after they occur" },
    { front: "Student engagement", back: "Active participation in learning" },
    { front: "Differentiated instruction", back: "Adapting to varied learning needs" },
    { front: "Parent-teacher collaboration", back: "Working together for student success" },
  ],
  "Assessment": [
    { front: "Summative", back: "End of term/year evaluation" }, { front: "Rubric", back: "Scoring guide with criteria" },
    { front: "Reliability", back: "Consistency of assessment results" }, { front: "Portfolio", back: "Collection of student work samples" },
    { front: "Validity", back: "Assessment measures what it intends to" },
    { front: "Norm-referenced", back: "Compare to other students" },
    { front: "Criterion-referenced", back: "Compare to set standard" },
    { front: "Diagnostic assessment", back: "Identify learning gaps before teaching" },
    { front: "Self-assessment", back: "Students evaluate own work" },
    { front: "Peer assessment", back: "Students evaluate each other's work" },
    { front: "Objective test", back: "Fixed answers (MCQ, T/F)" },
    { front: "Subjective test", back: "Open-ended answers (essay)" },
    { front: "Bloom's lowest level", back: "Remember / Knowledge" },
  ],
  "Literature": [
    { front: "Shakespeare", back: "Plays & Sonnets (1564-1616)" },
    { front: "Hamlet genre", back: "Tragedy" }, { front: "Haiku lines", back: "3 (5-7-5 syllables)" },
    { front: "Sonnet lines", back: "14" },
    { front: "Epic", back: "Long narrative poem (Iliad, Ramayana)" },
    { front: "Allegory", back: "Story with hidden meaning" },
    { front: "Satire", back: "Using humor to criticize" },
    { front: "Tragedy characteristic", back: "Hero's downfall due to fatal flaw" },
    { front: "Comedy ends with", back: "Happy resolution" },
    { front: "Protagonist", back: "Main character" },
    { front: "Antagonist", back: "Character opposing the protagonist" },
    { front: "Foreshadowing", back: "Hints about future events" },
    { front: "Irony types", back: "Verbal, Situational, Dramatic" },
  ],
  "History": [
    { front: "Harappan = ", back: "Indus Valley Civilization (~2500 BCE)" },
    { front: "French Revolution", back: "1789" },
    { front: "WWI started", back: "1914" }, { front: "Berlin Wall fell", back: "1989" },
    { front: "Magna Carta", back: "1215 — limited king's power" },
    { front: "Renaissance period", back: "14th-17th century" },
    { front: "American Independence", back: "1776" },
    { front: "Russian Revolution", back: "1917" },
    { front: "WWII ended", back: "1945" },
    { front: "Cold War period", back: "1947-1991" },
    { front: "Maurya Empire founder", back: "Chandragupta Maurya" },
    { front: "Mughal Empire founder", back: "Babur (1526)" },
    { front: "Salt March", back: "1930 — Gandhi's civil disobedience" },
    { front: "UN founded", back: "1945, after WWII" },
  ],
  "Economics": [
    { front: "GDP", back: "Gross Domestic Product — total output of a country" },
    { front: "Inflation", back: "Sustained rise in general price level" },
    { front: "Wealth of Nations", back: "Adam Smith (1776)" },
    { front: "Fiscal policy", back: "Government spending & taxation" },
    { front: "Monetary policy", back: "Central bank controls money supply" },
    { front: "Supply and Demand", back: "Price determined by intersection" },
    { front: "Opportunity cost", back: "Value of next best alternative forgone" },
    { front: "Elasticity", back: "Responsiveness of quantity to price change" },
    { front: "Monopoly", back: "Single seller dominates market" },
    { front: "Oligopoly", back: "Few sellers dominate market" },
    { front: "CPI", back: "Consumer Price Index — measures inflation" },
    { front: "Trade deficit", back: "Imports > Exports" },
    { front: "Mixed economy", back: "Both private and public sectors (India)" },
  ],
  "Political Science": [
    { front: "Democracy", back: "Rule by the people" }, { front: "UN founded", back: "1945" },
    { front: "India Constitution", back: "Adopted Jan 26, 1950" }, { front: "Lok Sabha seats", back: "545" },
    { front: "Rajya Sabha seats", back: "245" },
    { front: "Federalism", back: "Division of power between center and states" },
    { front: "Secularism", back: "State treats all religions equally" },
    { front: "Fundamental Rights", back: "6 rights in Part III of Constitution" },
    { front: "Directive Principles", back: "Part IV — guidelines for government" },
    { front: "Supreme Court judges", back: "CJI + 33 judges (max 34)" },
    { front: "Amendment process", back: "Article 368" },
    { front: "Emergency types", back: "National (352), State (356), Financial (360)" },
    { front: "Preamble keywords", back: "Sovereign, Socialist, Secular, Democratic, Republic" },
  ],
  "Psychology": [
    { front: "Father of Psychology", back: "Wilhelm Wundt" }, { front: "Id/Ego/Superego", back: "Freud's personality structure" },
    { front: "Classical conditioning", back: "Pavlov — stimulus-response learning" },
    { front: "IQ", back: "Intelligence Quotient" },
    { front: "Maslow's hierarchy", back: "Physiological → Safety → Love → Esteem → Self-actualization" },
    { front: "CBT", back: "Cognitive Behavioral Therapy" },
    { front: "Defense mechanisms", back: "Denial, Projection, Displacement, etc." },
    { front: "Short-term memory", back: "~7 items, ~20 seconds" },
    { front: "Long-term memory types", back: "Explicit (declarative) + Implicit (procedural)" },
    { front: "REM sleep", back: "Rapid Eye Movement — dreaming phase" },
    { front: "Cognitive dissonance", back: "Discomfort from conflicting beliefs" },
    { front: "Bystander effect", back: "Less likely to help when others present" },
    { front: "Stanford prison experiment", back: "Zimbardo — power of social roles" },
  ],
  "Human Anatomy": [
    { front: "Largest bone", back: "Femur" }, { front: "Heart chambers", back: "4" },
    { front: "Cranial nerves", back: "12 pairs" }, { front: "Vertebrae", back: "33" },
    { front: "Blood volume (adult)", back: "~5 liters" },
    { front: "Largest internal organ", back: "Liver" },
    { front: "Smallest bone", back: "Stapes (in ear)" },
    { front: "Diaphragm function", back: "Main muscle of breathing" },
    { front: "Kidney function", back: "Filter blood, produce urine" },
    { front: "Cerebellum function", back: "Balance and coordination" },
    { front: "Pancreas function", back: "Insulin production + digestive enzymes" },
    { front: "Lymph nodes function", back: "Filter lymph, immune defense" },
    { front: "Cartilage types", back: "Hyaline, Elastic, Fibrocartilage" },
    { front: "Synovial joint", back: "Freely movable joint with fluid" },
  ],
  "Microbiology": [
    { front: "Bacteria", back: "Single-celled prokaryotes" },
    { front: "Gram stain", back: "Differentiates Gram +ve (purple) and -ve (pink)" },
    { front: "Autoclave uses", back: "Moist heat under pressure (121°C, 15 psi)" },
    { front: "COVID-19 cause", back: "SARS-CoV-2 virus" },
    { front: "Koch's postulates", back: "4 criteria to prove causative agent" },
    { front: "Virus", back: "Non-living obligate intracellular parasite" },
    { front: "Fungi examples", back: "Candida, Aspergillus, Dermatophytes" },
    { front: "Antibiotic resistance", back: "Bacteria evolve to resist drugs" },
    { front: "PCR stands for", back: "Polymerase Chain Reaction" },
    { front: "ELISA", back: "Enzyme-Linked Immunosorbent Assay" },
    { front: "Normal flora", back: "Beneficial microorganisms living in body" },
    { front: "Sterilization vs Disinfection", back: "Kill all vs Reduce to safe level" },
    { front: "Nosocomial infection", back: "Hospital-acquired infection" },
  ],
  "Clinical Lab": [
    { front: "CBC tests", back: "Complete Blood Count — RBC, WBC, Platelets" },
    { front: "Normal WBC", back: "4000-11000/µL" },
    { front: "ESR measures", back: "Rate of RBC settling — inflammation marker" },
    { front: "Universal donor", back: "O negative" },
    { front: "Universal recipient", back: "AB positive" },
    { front: "Hemoglobin normal (male)", back: "14-18 g/dL" },
    { front: "Blood glucose fasting", back: "70-100 mg/dL" },
    { front: "HbA1c normal", back: "< 5.7%" },
    { front: "Serum creatinine normal", back: "0.7-1.3 mg/dL" },
    { front: "Urinalysis checks", back: "Color, pH, protein, glucose, blood" },
    { front: "Coagulation tests", back: "PT, aPTT, INR" },
    { front: "Blood culture purpose", back: "Detect bacteremia/sepsis" },
    { front: "Microscopy stains", back: "Gram, Ziehl-Neelsen, Giemsa" },
  ],
  "Radiology": [
    { front: "X-rays by", back: "Wilhelm Röntgen (1895)" },
    { front: "CT uses", back: "Multiple X-ray images for cross-sections" },
    { front: "MRI uses", back: "Magnetic fields + radio waves" },
    { front: "Lead apron protects", back: "Against ionizing radiation" },
    { front: "Ultrasound frequency", back: "> 20,000 Hz" },
    { front: "PET scan uses", back: "Radioactive tracers for metabolic imaging" },
    { front: "Contrast media purpose", back: "Enhance visibility of structures" },
    { front: "Fluoroscopy", back: "Real-time X-ray imaging" },
    { front: "Mammography", back: "Breast X-ray screening" },
    { front: "Radiation unit (dose)", back: "Gray (Gy) or Sievert (Sv)" },
    { front: "ALARA principle", back: "As Low As Reasonably Achievable" },
    { front: "Barium swallow", back: "GI tract imaging with barium contrast" },
  ],
  "Nursing Care": [
    { front: "Normal temp (°F)", back: "98.6°F / 37°C" },
    { front: "Pulse at", back: "Radial artery (wrist)" },
    { front: "Stethoscope by", back: "René Laennec (1816)" },
    { front: "Triage", back: "Sorting patients by severity" },
    { front: "5 vital signs", back: "Temp, Pulse, BP, Respiration, Pain" },
    { front: "Normal respiratory rate", back: "12-20 breaths/min (adult)" },
    { front: "Aseptic technique", back: "Prevent contamination during procedures" },
    { front: "Hand hygiene duration", back: "20 seconds minimum" },
    { front: "Nursing process steps", back: "Assessment, Diagnosis, Planning, Implementation, Evaluation" },
    { front: "Patient positioning types", back: "Supine, Prone, Lateral, Fowler's, Trendelenburg" },
    { front: "Glasgow Coma Scale", back: "Eye + Verbal + Motor (3-15)" },
    { front: "IV fluid types", back: "Normal Saline, Ringer's Lactate, D5W" },
    { front: "Medication rights", back: "Right patient, drug, dose, route, time" },
  ],
  "EVS": [
    { front: "What do plants need to grow?", back: "Sunlight, Water, Air, Soil 🌱" },
    { front: "3 states of water", back: "Solid (ice), Liquid (water), Gas (steam)" },
    { front: "Parts of a plant", back: "Root, Stem, Leaf, Flower, Fruit" },
    { front: "Water cycle steps", back: "Evaporation → Condensation → Precipitation" },
    { front: "Which season is hottest?", back: "Summer ☀️" },
    { front: "Name 3 domestic animals", back: "Dog, Cow, Cat" },
    { front: "What is recycling?", back: "Reusing waste materials ♻️" },
    { front: "What gives us rain?", back: "Clouds ☁️" },
    { front: "Who helps when we are sick?", back: "Doctor 👨‍⚕️" },
    { front: "Why should we plant trees?", back: "For oxygen, shade, and clean air 🌳" },
  ],
  "Biology": [
    { front: "Cell is the", back: "Basic unit of life" },
    { front: "DNA full form", back: "Deoxyribonucleic Acid" },
    { front: "Mitochondria function", back: "Powerhouse of the cell — produces ATP" },
    { front: "Cell division types", back: "Mitosis (growth) and Meiosis (gametes)" },
    { front: "Chromosomes in humans", back: "46 (23 pairs)" },
    { front: "Photosynthesis equation", back: "6CO₂ + 6H₂O → C₆H₁₂O₆ + 6O₂" },
    { front: "Blood groups", back: "A, B, AB, O" },
    { front: "Universal donor", back: "O negative" },
    { front: "Krebs cycle location", back: "Mitochondrial matrix" },
    { front: "Mendel is father of", back: "Genetics" },
    { front: "RNA full form", back: "Ribonucleic Acid" },
    { front: "Ecosystem components", back: "Biotic (living) + Abiotic (non-living)" },
    { front: "Food chain order", back: "Producer → Primary → Secondary → Tertiary consumer" },
    { front: "Endocrine system", back: "Hormone-producing glands" },
  ],
  "Tamil Basics": [
    { front: "அ", back: "First vowel — 'a' sound" },
    { front: "ஆ", back: "Long 'aa' sound" },
    { front: "இ", back: "Short 'i' sound" },
    { front: "உ", back: "Short 'u' sound" },
    { front: "க", back: "First consonant — 'ka' sound" },
    { front: "How many Tamil vowels?", back: "12 (உயிர் எழுத்துக்கள்)" },
    { front: "How many Tamil consonants?", back: "18 (மெய் எழுத்துக்கள்)" },
    { front: "அம்மா", back: "Mother 👩" },
    { front: "அப்பா", back: "Father 👨" },
    { front: "பூ", back: "Flower 🌸" },
  ],
  "Numbers (1-20)": [
    { front: "1", back: "One ☝️" }, { front: "2", back: "Two ✌️" },
    { front: "5", back: "Five 🖐️" }, { front: "10", back: "Ten 🔟" },
    { front: "11", back: "Eleven" }, { front: "15", back: "Fifteen" },
    { front: "20", back: "Twenty" },
    { front: "What comes after 15?", back: "16" },
    { front: "12 + 8 = ?", back: "20" },
    { front: "20 - 7 = ?", back: "13" },
  ],
  "Alphabets (A-Z)": [
    { front: "A", back: "🍎 Apple" }, { front: "B", back: "🏀 Ball" },
    { front: "C", back: "🐱 Cat" }, { front: "D", back: "🐶 Dog" },
    { front: "Z", back: "🦓 Zebra" },
  ],
};
